"""New orbital interface (stubs only, no logic).

Design: each flavor owns its validated spec and its own ``OrbitalData``
container. No factories, no entry-point lookup, no shared generic
container. Flavor is part of the node type, so ``valid_type`` and
``QueryBuilder`` distinguish it.
"""

from __future__ import annotations

import dataclasses


@dataclasses.dataclass
class RealhydrogenOrbitalSpec:
    position: tuple[float, float, float]
    angular_momentum: int
    magnetic_number: int
    radial_nodes: int
    kind_name: str | None = None
    spin: int = 0
    @property
    def name(self) -> str: ...
    @property
    def shell(self) -> str: ...
    @classmethod
    def get_name_from_quantum_numbers(cls, angular_momentum: int, magnetic_number: int | None = None) -> str: ...
    @classmethod
    def get_quantum_numbers_from_name(cls, name: str) -> list[dict]: ...


@dataclasses.dataclass
class SpinorbitOrbitalSpec:
    position: tuple[float, float, float]
    angular_momentum: int
    total_angular_momentum: float
    magnetic_number: float
    radial_nodes: int
    kind_name: str | None = None
    @property
    def shell(self) -> str: ...
    @property
    def label(self) -> str: ...


class RealhydrogenOrbitalData:
    @classmethod
    def get_name_from_quantum_numbers(cls, angular_momentum: int, magnetic_number: int | None = None) -> str: ...
    @classmethod
    def get_quantum_numbers_from_name(cls, name: str) -> list[dict]: ...
    @staticmethod
    def create(position, angular_momentum: int, magnetic_number: int, radial_nodes: int, **kwargs) -> RealhydrogenOrbitalSpec: ...
    def set_orbitals(self, orbitals: RealhydrogenOrbitalSpec | list[RealhydrogenOrbitalSpec]) -> None: ...
    def get_orbitals(self, **filters) -> list[RealhydrogenOrbitalSpec]: ...
    @property
    def kinds(self) -> list: ...
    @property
    def names(self) -> list[str]: ...
    @property
    def spins(self) -> list[int]: ...
    def get_by_kind(self, kind_name: str) -> list[RealhydrogenOrbitalSpec]: ...
    def get_by_shell(self, shell: str) -> list[RealhydrogenOrbitalSpec]: ...
    def get_by_spin(self, spin: int) -> list[RealhydrogenOrbitalSpec]: ...
    def count_by_kind(self) -> dict: ...
    def count_by_spin(self) -> dict[int, int]: ...


class SpinorbitOrbitalData:
    @staticmethod
    def create(position, angular_momentum: int, total_angular_momentum: float, magnetic_number: float, radial_nodes: int, **kwargs) -> SpinorbitOrbitalSpec: ...
    def set_orbitals(self, orbitals: SpinorbitOrbitalSpec | list[SpinorbitOrbitalSpec]) -> None: ...
    def get_orbitals(self, **filters) -> list[SpinorbitOrbitalSpec]: ...
    @property
    def kinds(self) -> list: ...
    @property
    def labels(self) -> list[str]: ...
    def get_by_kind(self, kind_name: str) -> list[SpinorbitOrbitalSpec]: ...
    def get_by_j(self, total_angular_momentum: float) -> list[SpinorbitOrbitalSpec]: ...
    def count_by_kind(self) -> dict: ...
