###########################################################################
# Copyright (c), The AiiDA team. All rights reserved.                     #
# This file is part of the AiiDA code.                                    #
#                                                                         #
# The code is hosted on GitHub at https://github.com/aiidateam/aiida-core #
# For further information on the license, see the LICENSE.txt file        #
# For further information please visit http://www.aiida.net               #
###########################################################################
"""Apply privacy decisions from a public API review.

The input is any checklist generated by ``generate_api_review.py``. Decisions
``n`` and ``m`` are both treated as private, while ``y`` is public. If every
top-level resource in a source module is private, the module is prefixed with
an underscore. Otherwise, rejected top-level resources are prefixed
individually. Child decisions must agree with their top-level class decision.

The command only reports its plan unless ``--apply`` is passed.
"""

from __future__ import annotations

import argparse
import ast
import io
import json
import tokenize
from collections import defaultdict
from dataclasses import asdict, dataclass
from importlib.util import resolve_name
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SEARCH_ROOTS = ('src', 'tests', 'utils')
DECISIONS = {'y', 'm', 'n'}


@dataclass(frozen=True)
class ReviewEntry:
    """A reviewed API resource."""

    decision: str
    resource: str
    kind: str
    signature: str


@dataclass(frozen=True)
class PrivacyPlan:
    """Resources to mark private."""

    private_modules: tuple[str, ...]
    private_symbols: dict[str, tuple[str, ...]]


def parse_arguments() -> argparse.Namespace:
    """Return parsed command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('review', type=Path, help='Completed API review checklist.')
    parser.add_argument('--apply', action='store_true', help='Apply the reported changes.')
    parser.add_argument('--output-json', type=Path, help='Write the parsed decisions and privacy plan as JSON.')
    parser.add_argument(
        '--project-root',
        type=Path,
        default=PROJECT_ROOT,
        help='Root of the aiida-core checkout (default: %(default)s).',
    )
    return parser.parse_args()


def read_review(path: Path) -> list[ReviewEntry]:
    """Read and validate a completed review checklist."""
    entries = []
    for line_number, line in enumerate(path.read_text(encoding='utf-8').splitlines(), start=1):
        if not line or line.startswith('#'):
            continue
        fields = line.split('\t')
        if len(fields) < 3 or fields[0] not in DECISIONS:
            message = f'Invalid review record at {path}:{line_number}'
            raise ValueError(message)
        entries.append(
            ReviewEntry(
                decision=fields[0],
                resource=fields[1],
                kind=fields[2],
                signature='\t'.join(fields[3:]),
            )
        )

    unreviewed = [entry.resource for entry in entries if entry.decision == '_']
    if unreviewed:
        message = f'Review contains {len(unreviewed)} unreviewed resources.'
        raise ValueError(message)
    return entries


def get_source_modules(source_root: Path) -> dict[str, Path]:
    """Return non-private modules in the AiiDA source tree."""
    modules = {}
    for path in source_root.rglob('*.py'):
        relative = path.relative_to(source_root)
        parts = relative.parent.parts if path.name == '__init__.py' else (*relative.parent.parts, path.stem)
        if any(part.startswith('_') for part in parts):
            continue
        module = '.'.join(('aiida', *parts))
        modules[module] = path
    return modules


def build_plan(entries: list[ReviewEntry], source_root: Path) -> PrivacyPlan:
    """Build and validate a privacy plan from reviewed resources."""
    modules = get_source_modules(source_root)
    grouped: dict[str, list[ReviewEntry]] = defaultdict(list)

    for entry in entries:
        candidates = [module for module in modules if entry.resource.startswith(f'{module}.')]
        if not candidates:
            message = f'Review resource is not in a public AiiDA source module: {entry.resource}'
            raise ValueError(message)
        grouped[max(candidates, key=len)].append(entry)

    private_modules = []
    private_symbols: dict[str, tuple[str, ...]] = {}
    for module, module_entries in sorted(grouped.items()):
        prefix = f'{module}.'
        top_level: dict[str, ReviewEntry] = {}
        descendants: dict[str, list[ReviewEntry]] = defaultdict(list)

        for entry in module_entries:
            relative = entry.resource.removeprefix(prefix)
            symbol = relative.split('.', maxsplit=1)[0]
            if '.' not in relative:
                top_level[symbol] = entry
            else:
                descendants[symbol].append(entry)

        missing = descendants.keys() - top_level.keys()
        if missing:
            message = f'Missing top-level review entries in {module}: {", ".join(sorted(missing))}'
            raise ValueError(message)

        for symbol, children in descendants.items():
            expected_private = top_level[symbol].decision in {'m', 'n'}
            inconsistent = [child.resource for child in children if (child.decision in {'m', 'n'}) != expected_private]
            if inconsistent:
                message = f'Child decisions conflict with `{prefix}{symbol}`: {", ".join(inconsistent)}'
                raise ValueError(message)

        rejected = tuple(sorted(symbol for symbol, entry in top_level.items() if entry.decision in {'m', 'n'}))
        if rejected:
            private_symbols[module] = rejected
        if rejected and len(rejected) == len(top_level):
            private_modules.append(module)

    return PrivacyPlan(tuple(private_modules), private_symbols)


def remove_module_exports(source: str, rejected: set[str]) -> str:
    """Remove rejected names from a module's literal ``__all__``."""
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)
    offsets = [0]
    for line in lines:
        offsets.append(offsets[-1] + len(line))

    for node in tree.body:
        if not isinstance(node, ast.Assign) or not any(
            isinstance(target, ast.Name) and target.id == '__all__' for target in node.targets
        ):
            continue
        if not isinstance(node.value, (ast.List, ast.Tuple)) or not all(
            isinstance(item, ast.Constant) and isinstance(item.value, str) for item in node.value.elts
        ):
            message = 'Expected `__all__` to be a literal list or tuple of strings.'
            raise ValueError(message)
        values = [
            item.value for item in node.value.elts if isinstance(item, ast.Constant) and item.value not in rejected
        ]
        expression = repr(tuple(values)) if isinstance(node.value, ast.Tuple) else repr(values)
        assert node.value.end_lineno is not None and node.value.end_col_offset is not None
        start = offsets[node.value.lineno - 1] + node.value.col_offset
        end = offsets[node.value.end_lineno - 1] + node.value.end_col_offset
        return source[:start] + expression + source[end:]

    message = 'Expected module with partially private resources to define `__all__`.'
    raise ValueError(message)


def rename_identifier_tokens(source: str, renames: dict[str, str]) -> str:
    """Rename identifier tokens without changing strings or comments."""
    tokens = []
    for token in tokenize.generate_tokens(io.StringIO(source).readline):
        rewritten = token
        if token.type == tokenize.NAME and token.string in renames:
            rewritten = tokenize.TokenInfo(token.type, renames[token.string], token.start, token.end, token.line)
        tokens.append(rewritten)
    return tokenize.untokenize(tokens)


def rewrite_import_statement(
    node: ast.Import | ast.ImportFrom, plan: PrivacyPlan, current_package: str | None = None
) -> str | None:
    """Return a rewritten import statement, if the plan affects it."""
    private_modules = set(plan.private_modules)

    if isinstance(node, ast.Import):
        changed = False
        aliases = []
        for alias in node.names:
            rewritten = alias
            name = alias.name
            if name in private_modules:
                private_name = name.rsplit('.', maxsplit=1)[0] + '._' + name.rsplit('.', maxsplit=1)[1]
                rewritten = ast.alias(name=private_name, asname=alias.asname or name.rsplit('.', maxsplit=1)[1])
                changed = True
            aliases.append(rewritten)
        return ast.unparse(ast.Import(names=aliases)) if changed else None

    module = node.module
    aliases = list(node.names)
    changed = False
    level = node.level
    if level and current_package is not None:
        relative_name = '.' * level + (module or '')
        module = resolve_name(relative_name, current_package)
        level = 0
    if module in private_modules:
        module = module.rsplit('.', maxsplit=1)[0] + '._' + module.rsplit('.', maxsplit=1)[1]
        changed = True
    elif module in plan.private_symbols:
        rejected = set(plan.private_symbols[module])
        new_aliases = []
        for alias in aliases:
            rewritten = alias
            if alias.name in rejected:
                rewritten = ast.alias(name=f'_{alias.name}', asname=alias.asname or alias.name)
                changed = True
            new_aliases.append(rewritten)
        aliases = new_aliases
    elif module is not None:
        child_private_modules = {
            private_module.rsplit('.', maxsplit=1)[1]: private_module
            for private_module in private_modules
            if private_module.rpartition('.')[0] == module
        }
        symbol_modules: dict[str, str] = {}
        for owner_module, symbols in plan.private_symbols.items():
            if owner_module.rpartition('.')[0] != module:
                continue
            for symbol in symbols:
                if symbol in symbol_modules:
                    message = f'Ambiguous private resource name in {module}: {symbol}'
                    raise ValueError(message)
                symbol_modules[symbol] = owner_module

        remaining = []
        private_imports = []
        for alias in aliases:
            private_module = child_private_modules.get(alias.name)
            if private_module is not None:
                private_imports.append(
                    ast.ImportFrom(
                        module=module,
                        names=[ast.alias(name=f'_{alias.name}', asname=alias.asname or alias.name)],
                        level=0,
                    )
                )
                continue

            defining_module = symbol_modules.get(alias.name)
            if defining_module is None:
                remaining.append(alias)
                continue
            target_module = defining_module
            target_name = alias.name
            if defining_module in private_modules:
                target_module = (
                    defining_module.rsplit('.', maxsplit=1)[0] + '._' + defining_module.rsplit('.', maxsplit=1)[1]
                )
            else:
                target_name = f'_{target_name}'
            private_imports.append(
                ast.ImportFrom(
                    module=target_module,
                    names=[ast.alias(name=target_name, asname=alias.asname or alias.name)],
                    level=0,
                )
            )

        if private_imports:
            statements = private_imports
            if remaining:
                statements.insert(0, ast.ImportFrom(module=module, names=remaining, level=level))
            return '; '.join(ast.unparse(statement) for statement in statements)

    return ast.unparse(ast.ImportFrom(module=module, names=aliases, level=level)) if changed else None


def rewrite_imports(source: str, plan: PrivacyPlan, current_package: str | None = None) -> str:
    """Rewrite imports and qualified paths affected by ``plan``."""
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)
    offsets = [0]
    for line in lines:
        offsets.append(offsets[-1] + len(line))

    edits = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Import, ast.ImportFrom)):
            continue
        replacement = rewrite_import_statement(node, plan, current_package)
        if replacement is None:
            continue
        assert node.end_lineno is not None and node.end_col_offset is not None
        start = offsets[node.lineno - 1] + node.col_offset
        end = offsets[node.end_lineno - 1] + node.end_col_offset
        edits.append((start, end, replacement))

    for start, end, replacement in sorted(edits, reverse=True):
        source = source[:start] + replacement + source[end:]

    for module in plan.private_modules:
        private_module = module.rsplit('.', maxsplit=1)[0] + '._' + module.rsplit('.', maxsplit=1)[1]
        source = source.replace(module, private_module)
    for module, symbols in plan.private_symbols.items():
        for symbol in symbols:
            source = source.replace(f'{module}.{symbol}', f'{module}._{symbol}')
    return source


def iter_python_files(project_root: Path) -> list[Path]:
    """Return Python files whose imports may require updating."""
    return sorted(path for root in SEARCH_ROOTS for path in (project_root / root).rglob('*.py'))


def apply_plan(plan: PrivacyPlan, project_root: Path) -> None:
    """Apply ``plan`` to source files."""
    source_root = project_root / 'src' / 'aiida'
    source_modules = get_source_modules(source_root)
    modules_by_path = {path: module for module, path in source_modules.items()}

    for path in iter_python_files(project_root):
        source = path.read_text(encoding='utf-8')
        module = modules_by_path.get(path)
        current_package = None
        if module is not None:
            current_package = module if path.name == '__init__.py' else module.rpartition('.')[0]
        rewritten = rewrite_imports(source, plan, current_package)
        if module in plan.private_symbols and module not in plan.private_modules:
            rejected = set(plan.private_symbols[module])
            rewritten = remove_module_exports(rewritten, rejected)
            rewritten = rename_identifier_tokens(rewritten, {symbol: f'_{symbol}' for symbol in rejected})
        if rewritten != source:
            path.write_text(rewritten, encoding='utf-8')

    for module in sorted(plan.private_modules, key=lambda value: value.count('.'), reverse=True):
        source_path = source_modules[module]
        if source_path.name == '__init__.py':
            if module == 'aiida':
                message = 'The top-level `aiida` package cannot be marked private.'
                raise ValueError(message)
            source_path = source_path.parent
            destination = source_path.with_name(f'_{source_path.name}')
        else:
            destination = source_path.with_name(f'_{source_path.name}')
        if destination.exists():
            message = f'Refusing to overwrite existing module: {destination}'
            raise FileExistsError(message)
        source_path.rename(destination)


def main() -> None:
    """Report or apply the privacy plan."""
    arguments = parse_arguments()
    project_root = arguments.project_root.resolve()
    entries = read_review(arguments.review)
    plan = build_plan(entries, project_root / 'src' / 'aiida')

    print('Modules to mark private:')
    for module in plan.private_modules:
        print(f'  {module}')
    print('Resources to mark private within otherwise public modules:')
    for module, symbols in plan.private_symbols.items():
        if module not in plan.private_modules:
            for symbol in symbols:
                print(f'  {module}.{symbol}')

    if arguments.output_json:
        payload = {'review': [asdict(entry) for entry in entries], 'plan': asdict(plan)}
        arguments.output_json.write_text(json.dumps(payload, indent=2) + '\n', encoding='utf-8')

    if not arguments.apply:
        print('Dry run only; pass --apply to modify files.')
        return
    apply_plan(plan, project_root)
    print('Migration applied.')


if __name__ == '__main__':
    main()
